Feat: 상품 정보 조회 구현
MultiProject23/Shop_SemiProject pull request #32
Opened 2023-03-31 12:20 UTC by rrimm

# 개요

```text

#(14)
상품의 정보 조회 구현

```

## 할 일

```text

- [ ] 상품 정보 조회 관련 비즈니스 로직 구현

```

## ETC

2023-04-01 05:42 UTC, rrimm commented
> # 개요
> #14 상품의 정보 조회 구현
> 
> ## 내용
> *   상품의 carousel 조회 기능 구현
> *   존재하지 않는 상품 조회 시 예외처리 구현

2023-04-01 07:18 UTC, KIMSEI1124 requested changes
리뷰 달아둔 내용을 수정해주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/exception/ProductErrorCode.java
> +    PRODUCT_NOT_FOUND(500, "PRODUCT_01", "존재하지 않는 상품입니다.");
500이 아닌 400으로 수정해주세요.
500은 서버의 오류 입니다.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/resources/mapper/product/ProductMapper.xml
`existByProductId`라는 반환 타입은 `boolean` 으로 하나 작성하셔야 합니다.
`true` 는 1로 반환하시고 `false` 는 0으로 반환해야 합니다.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/member/domain/dao/MemberJoinDAO.java
> +//dao: 어떤 테이블에 어떤 행위를 할지
주석 삭제 해주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/controller/ProductController.java
> +    }
`findByProductId`로 수정해주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/domain/vo/ProductVO.java
> +@Data
`@Getter` 어노테이션으로 사용해주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/dto/response/ProductResponse.java
> +//DAO (Data Access Object): 데이터베이스에 접근하여 데이터를 조작하는 객체
주석 삭제해주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/exception/ProductException.java
> +
공백 삭제해주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/mapper/ProductMapper.java
> +   ProductVO findByProductId(Long productId);
`findByProductId`로 수정해주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/repository/ProductRepository.java
> +    }
17번 행의 공백을 삭제해 주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/service/ProductService.java
> +    }
`existByProductId` 의 메서드를 만들어서 해주세요.
`null` 로 확인하는  것이 아닌 `boolean` 으로 확인해주세요.

2023-04-01 07:18 UTC, KIMSEI1124 commented on front-end/.env
삭제해주세요.

2023-04-01 09:31 UTC, KIMSEI1124 commented
# 순서

제가 생각한 `commit` 순서

1. refactor
2. remove
3. fix
4. feat

2023-04-01 09:47 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/exception/ProductErrorCode.java
> +    PRODUCT_NOT_FOUND(500, "PRODUCT_01", "존재하지 않는 상품입니다.");
수정 완료하였습니다! 001bf46

2023-04-01 09:48 UTC, rrimm commented on back-end/src/main/resources/mapper/product/ProductMapper.xml
수정 완료하였습니다! 001bf46

2023-04-01 09:48 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/member/domain/dao/MemberJoinDAO.java
> +//dao: 어떤 테이블에 어떤 행위를 할지
주석 삭제하였습니다! 001bf46

2023-04-01 09:48 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/controller/ProductController.java
> +    }
수정 완료하였습니다! 001bf46

2023-04-01 09:49 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/domain/vo/ProductVO.java
> +@Data
어노테이션 변경하였습니다. 001bf46

2023-04-01 09:50 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/exception/ProductException.java
> +
공백 삭제하였습니다. 001bf46

2023-04-01 09:50 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/repository/ProductRepository.java
> +    }
수정 완료하였습니다. 001bf46

2023-04-01 09:51 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/service/ProductService.java
> +    }
메서드 생성 완료하였습니다. 001bf46

2023-04-01 09:51 UTC, rrimm commented on front-end/.env
파일 삭제 완료했습니다. 001bf46

2023-04-01 10:20 UTC, KIMSEI1124 requested changes
리뷰 결과 기능을 추가 해야 할 것 같습니다.

2023-04-01 10:20 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/dto/response/ProductsResponse.java
> +    public static ProductsResponse of(ProductVO vo) {
`from` 로 변경

[[Java] Method Naming Convention (feat. of vs from)](https://siahn95.tistory.com/entry/Java-Method-Naming-Convention-feat-of-vs-from)

2023-04-01 10:20 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/service/ProductService.java
> +        }
# 검증용 메서드로 분리

- `validateProductIsExistById` 의 함수명으로 분리
- 있을 경우 `true` 로 값을 가져와 예외 처리 기능 수행

2023-04-01 10:20 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/service/ProductService.java
> +    }
# 순서

1. `productId` 제품을 먼저 찾는다. -> `productVO`
2. `productId`, `category`, `target`를 가진 객체 만든다. ( `dto`, `vo` )
3. `repository` 로 보내고 `mapper` 를 보낸다.

2023-04-01 10:20 UTC, KIMSEI1124 commented on back-end/src/main/resources/mapper/product/ProductMapper.xml
> +    </select>
# 결과를 제한

- `limit` 를 10개? 편하신대로 설정
- `WHERE` or `sub query` 사용하여 `productId`의 제품은 제외

2023-04-01 10:35 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/dto/response/ProductsResponse.java
> +    public static ProductsResponse of(ProductVO vo) {
변경 완료하였습니다. eeaea19

2023-04-01 11:22 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/service/ProductService.java
> +        }
수정 완료하였습니다. 7a03917

2023-04-01 13:22 UTC, rrimm commented on back-end/src/main/resources/mapper/product/ProductMapper.xml
> +    </select>
수정 완료하였습니다. acb5cde

2023-04-02 03:31 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/service/ProductService.java
> +    }
수정하였습니다. 7059923

2023-04-02 06:26 UTC, rrimm commented on back-end/src/main/java/com/multi/shop/product/service/ProductService.java
> +    }
재수정 완료하였습니다! 2ae774a

2023-04-02 06:51 UTC, KIMSEI1124 requested changes
수정하시면 머지하겠습니다.

2023-04-02 06:51 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/dto/response/ProductsResponse.java
> +//DAO (Data Access Object): 데이터베이스에 접근하여 데이터를 조작하는 객체
주석 삭제 해주세요.

2023-04-02 06:51 UTC, KIMSEI1124 commented on back-end/src/main/java/com/multi/shop/product/controller/ProductController.java
> +    public ResponseEntity<List<ProductsResponse>> findRelatedProductsByProductId(@PathVariable Long id) {
# 피드백

`findRelatedProductsByProductId` -> `findRelatedProducts`로 함수명 수정해주세요.

2023-04-02 07:13 UTC, KIMSEI1124 approved these changes
머지하겠습니다.

2023-04-02 07:14 UTC, merged